### ISSUE TITLE
blink-diff unable to finish read stream

### ISSUE THREAD

**Issue by NimaSoroush** [matteofigus/mirror-mirror#59]
Hi @matteofigus,

I got a strange problem with running some test, which starts failing from time to time. The exception happening because blink-diff fails to get access to generated screenshot (just a guess). Here is the exception log:

```
/Users/x/components/header/node_modules/blink-diff/index.js:355
            throw new Error('ERROR: ' + text);
            ^

Error: ERROR: There are some read requests waitng on finished stream
    at Object.<anonymous> (/Users/x/components/header/node_modules/blink-diff/index.js:355:10)
    at .<anonymous> (/Users/x/components/header/node_modules/pngjs-image/index.js:28:12)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at ChunkStream._end (/Users/x/components/header/node_modules/pngjs-image/node_modules/pngjs/lib/chunkstream.js:99:10)
    at ChunkStream.end (/Users/x/components/header/node_modules/pngjs-image/node_modules/pngjs/lib/chunkstream.js:86:10)
    at PNG.end (/Users/x/components/header/node_modules/pngjs-image/node_modules/pngjs/lib/png.js:97:16)
    at ReadStream.onend (_stream_readable.js:511:10)
```

I just found out that blink-diff not been maintained anymore. https://github.com/yahoo/blink-diff/issues/39

Should mirror-mirror use some other diffing lib?!

**Comment by matteofigus** [comment]
Yeah, possibly yes. I liked blink-diff because it was very lightweight :(

Are you aware of any other good options?

**Comment by NimaSoroush** [comment]
I was looking some alternatives and my these two seems to be quite decent.
https://github.com/mapbox/pixelmatch
https://github.com/Huddle/Resemble.js

I might give them a try instead of digging into blink-diff issue
